---
- hosts: localhost
  become: yes
  vars:
    - homeDir: /home/ubuntu/
    - appDir : ansible

  tasks:
  - name: Git - Cloning/Syncing repository from CodeCommit
    git:
      repo: "https://github.com/yuvayrj1/ansibletest.git"
      dest: "{{homeDir}}/{{appDir}}"
        

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}
    register: npm_finished


  - name: Start APP
    command: "{{item}}" 
    with_items:
        - forever start {{homeDir}}/{{appDir}}/app.js
    ignore_errors: yes

  - name: backup to backup dir
    command: "{{ item }}"
    with_items:
        - cp -r /{{homeDir}}/{{appDir}}/ /tmp/{{appDir}}_rollback

