---
- hosts: localhost
  become: yes
  vars:
    - homeDir: /home/aximsoft/
    - appDir : ansible
       
  tasks:
  
  - name: roll_back
    command: "{{ item }}"
    with_items:
        - cp -r /{{homeDir}}/{{appDir}}/ /tmp/{{appDir}}_rollback_failure
        - cp -r /tmp/{{appDir}}_rollback /{{homeDir}}/{{appDir}}
          
  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/
    register: npm_finished
    
  - name: Start APP
    command:  forever start {{homeDir}}/{{appDir}}/app.js
    ignore_errors: yes
  
        

